### ISSUE TITLE
Weird entry names in .msi file

### ISSUE THREAD

**Issue by kjk** [SheetJS/js-cfb#3]
MSI file is also MS-CFB format.

I opened https://cmake.org/files/v3.11/cmake-3.11.1-win64-x64.msi with http://sheetjs.com/cfb-editor

The file can be opened and the content of entries seems to be correct but file names seem wrong:

![screen shot 2018-04-22 at 9 07 57 pm](https://user-images.githubusercontent.com/7935/39106561-58139800-4671-11e8-8bf0-e0f8fda46876.png)

**Comment by SheetJSDev** [comment]
Those are the actual entry names.

[MS-CFB 2.6.1](https://msdn.microsoft.com/en-us/library/dd942175.aspx) asserts the names are encoded in UTF-16.  Here are the actual bytes from the first four directory entries:

```
5200 6f00 6f00 7400 2000 4500 6e00 7400
7200 7900 0000
"Root Entry" (this is not included in the output)

3042 2743 6438 be41 6441 0000 
"䈰䌧㡤䆾䅤"

0500 5300 7500 6d00 6d00 6100 7200 7900
4900 6e00 6600 6f00 7200 6d00 6100 7400
6900 6f00 6e00 0000
"\u0005SummaryInformation"

4048 ff3f e443 ec41 e445 ac44 3148 0000
"䡀㿿䏤䇬䗤䒬䠱"
```

Since both the Root Entry and the [standard `\u0005SummaryInformation` stream](https://msdn.microsoft.com/en-us/library/dd910251.aspx) appear, I'm inclined to believe that MSI is doing something funky with the filenames.

And if [this blog post](http://robmensching.com/blog/posts/2004/2/10/inside-the-msi-file-format-again/) is to be believed, MSI is in fact doing something funky with the filenames:

> The Windows Installer actually compresses the stream names to double the space available to 62 or 63 characters (plus one extra for the null terminator, but again, who's counting?). That compression is why if you open a MSI file with dfview.exe you'll see a bunch of gobbledygook names. That compression algorithm is not documented so I can't comment on it.

**Comment by SheetJSDev** [comment]
We added the display to the website, reversing the algorithm based on the expected names in [the Installer Database documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa368259.aspx):

<img width="750" alt="screen shot 2018-04-23 at 13 40 45" src="https://user-images.githubusercontent.com/6070939/39143473-ffa60eb0-46fb-11e8-8f44-98721325f6a6.png">

**Comment by kjk** [comment]
Awesome, thanks!

**Comment by msauper** [comment]
can you describe the algorithm used to encode the names?

**Comment by SheetJSDev** [comment]
There's no official specification for this, which is why we haven't added it to the main project, but here's an example: `䡀䇊䌰㮱䈻䘦䈷䈜䘴䑨䈦`  A list of MSI database tables is in https://docs.microsoft.com/en-us/windows/desktop/Msi/database-tables so it's a reasonable guess that the stream name corresponds to one of those.  The code looks like:

```js
const decode_msi_char = (x) => {
  switch(true) {
    case x<10:  return x + 48;
    case x<36:  return x + 55;
    case x<62:  return x + 61;
    case x==62: return 46;
  }
  return 95;
};

const decode_msi_name = (instr) => {
  var ch = instr.charCodeAt(0);
  var idx = 0;
  var out = [];
  if(ch == 0x4840) ++idx; // TODO: is this actually supposed to be a null byte?
  while ((ch = instr.charCodeAt(idx++))) {
    if(ch >= 0x3800 && ch < 0x4840 ) {
      if(ch >= 0x4800) {
        ch = decode_msi_char(ch-0x4800);
      } else {
        ch -= 0x3800;
        out.push(String.fromCharCode(decode_msi_char(ch & 0x3f)));
        ch = decode_msi_char( (ch>>6) & 0x3f);
      }
    }
    out.push(String.fromCharCode(ch));
  }
  return out.join("");
};
```

Applying it to the example string gives you `AdminExecuteSequence`, sure enough an actual table name!

**Comment by msauper** [comment]
Thanks for your help.  This worked quite well.
